model:
  N: 2
  batch_size: 128
  d_ff: 256
  d_model: 128
  h: 2
  seq_length: 256
paths:
  data: ../online_dataset/imdb_processed.csv
  weights: ../saved_models/
testing:
  label: 1
  new_input: This movie was really good.
training:
  amount_of_data: 0.7
  device: mps
  epochs: 3
  learning_rate: 0.001
