# GENERAL PARAMETERS
model:
  batch_size: 64
  seq_length: 128
  N: 2
  d_model: 64
  d_ff: 128
  h: 2

training:
  amount_of_data: 1
  epochs: 5
  learning_rate: 0.001

paths:
  data: "../online_dataset/imdb_processed.csv"
  weights: "../saved_models/"

